export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const RESET_DATA_SUCCESS = 'RESET_DATA_SUCCESS';
export const ADD_ROOM_NUMBERS = 'ADD_ROOM_NUMBERS'

